DELIMITER $$

USE `sgauni512`$$

DROP PROCEDURE IF EXISTS `DELATE_CURSADO_ALUMNO`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `DELATE_CURSADO_ALUMNO`(IN dni INT(11))
DELETE FROM cursado WHERE `cur_alu_dni`=dni$$

DELIMITER ;