package com.uni.view.submenus.alumno;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author diego
 */
public class PanelAlumnoEliminacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarreraEdicion
     */
    public PanelAlumnoEliminacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_AlumnoNombre = new javax.swing.JTextField();
        txt_AlumnoDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_AlumnoApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_AlumnoCarreraNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_AlumnoCarreraCodigo = new javax.swing.JTextField();
        txt_AlumnoResidencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_AlumnoTelefono = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_InscripcionFecha = new javax.swing.JTextField();
        bt_ConfirmarEliminacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(388, 611));
        setPreferredSize(new java.awt.Dimension(300, 351));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 52, 52));
        jLabel1.setText("Eliminar Alumno");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(224, 52, 52))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("DNI:");

        txt_AlumnoNombre.setEditable(false);
        txt_AlumnoNombre.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoNombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setText("Nombre");
        txt_AlumnoNombre.setBorder(null);
        txt_AlumnoNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setDoubleBuffered(true);
        txt_AlumnoNombre.setSelectionColor(new java.awt.Color(255, 255, 255));

        txt_AlumnoDni.setEditable(false);
        txt_AlumnoDni.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoDni.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoDni.setText("Dni");
        txt_AlumnoDni.setBorder(null);
        txt_AlumnoDni.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoDni.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoDni.setDoubleBuffered(true);
        txt_AlumnoDni.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Apellido:");

        txt_AlumnoApellido.setEditable(false);
        txt_AlumnoApellido.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoApellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setText("Apellido");
        txt_AlumnoApellido.setBorder(null);
        txt_AlumnoApellido.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setDoubleBuffered(true);
        txt_AlumnoApellido.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Carrera Inscripto:");

        txt_AlumnoCarreraNombre.setEditable(false);
        txt_AlumnoCarreraNombre.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoCarreraNombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setText("Nombre Carrera");
        txt_AlumnoCarreraNombre.setBorder(null);
        txt_AlumnoCarreraNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setDoubleBuffered(true);
        txt_AlumnoCarreraNombre.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Codigo:");

        txt_AlumnoCarreraCodigo.setEditable(false);
        txt_AlumnoCarreraCodigo.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoCarreraCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setText("Codigo");
        txt_AlumnoCarreraCodigo.setBorder(null);
        txt_AlumnoCarreraCodigo.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setDoubleBuffered(true);
        txt_AlumnoCarreraCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));

        txt_AlumnoResidencia.setEditable(false);
        txt_AlumnoResidencia.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoResidencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setText("Lugar de residencia");
        txt_AlumnoResidencia.setBorder(null);
        txt_AlumnoResidencia.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setDoubleBuffered(true);
        txt_AlumnoResidencia.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Residencia:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Numero Telefonico:");

        txt_AlumnoTelefono.setEditable(false);
        txt_AlumnoTelefono.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setText("Telefono");
        txt_AlumnoTelefono.setBorder(null);
        txt_AlumnoTelefono.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setDoubleBuffered(true);
        txt_AlumnoTelefono.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Fecha de Inscripcion:");

        txt_InscripcionFecha.setEditable(false);
        txt_InscripcionFecha.setBackground(new java.awt.Color(102, 102, 102));
        txt_InscripcionFecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setText("0000-00-00");
        txt_InscripcionFecha.setBorder(null);
        txt_InscripcionFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setDoubleBuffered(true);
        txt_InscripcionFecha.setSelectionColor(new java.awt.Color(255, 255, 255));

        bt_ConfirmarEliminacion.setBackground(new java.awt.Color(224, 52, 52));
        bt_ConfirmarEliminacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bt_ConfirmarEliminacion.setForeground(new java.awt.Color(51, 51, 51));
        bt_ConfirmarEliminacion.setText("Eliminar");
        bt_ConfirmarEliminacion.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoCarreraCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_InscripcionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_ConfirmarEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_AlumnoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_AlumnoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_AlumnoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_AlumnoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_AlumnoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_AlumnoCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_AlumnoCarreraCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_InscripcionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(bt_ConfirmarEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(224, 52, 52));
        jPanel3.setForeground(new java.awt.Color(224, 52, 52));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    public JTextField getTxt_AlumnoApellido() {
        return txt_AlumnoApellido;
    }

    public JTextField getTxt_AlumnoCarreraCodigo() {
        return txt_AlumnoCarreraCodigo;
    }

    public JTextField getTxt_AlumnoCarreraNombre() {
        return txt_AlumnoCarreraNombre;
    }

    public JTextField getTxt_AlumnoDni() {
        return txt_AlumnoDni;
    }

    public JTextField getTxt_AlumnoNombre() {
        return txt_AlumnoNombre;
    }

    public JTextField getTxt_AlumnoResidencia() {
        return txt_AlumnoResidencia;
    }

    public JTextField getTxt_AlumnoTelefono() {
        return txt_AlumnoTelefono;
    }

    public JTextField getTxt_InscripcionFecha() {
        return txt_InscripcionFecha;
    }

    public void setTxt_InscripcionFecha(JTextField txt_InscripcionFecha) {
        this.txt_InscripcionFecha = txt_InscripcionFecha;
    }

    public JButton getBt_ConfirmarEliminacion() {
        return bt_ConfirmarEliminacion;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ConfirmarEliminacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_AlumnoApellido;
    private javax.swing.JTextField txt_AlumnoCarreraCodigo;
    private javax.swing.JTextField txt_AlumnoCarreraNombre;
    private javax.swing.JTextField txt_AlumnoDni;
    private javax.swing.JTextField txt_AlumnoNombre;
    private javax.swing.JTextField txt_AlumnoResidencia;
    private javax.swing.JTextField txt_AlumnoTelefono;
    private javax.swing.JTextField txt_InscripcionFecha;
    // End of variables declaration//GEN-END:variables
}
