package com.uni.view.submenus.alumno;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author diego
 */
public class PanelAlumnoEdicion extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarreraEdicion
     */
    public PanelAlumnoEdicion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_AlumnoNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_AlumnoApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_AlumnoCarreraNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_AlumnoCarreraCodigo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_SelectMateria = new javax.swing.JComboBox<>();
        bt_ConfirmAgregarMateria = new javax.swing.JButton();
        txt_AlumnoResidencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_AlumnoTelefono = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_InscripcionFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_AlumnoMaterias = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        bt_ConfirmarCambios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_SelectAlumno = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_SelectAlumnoDni = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(350, 611));
        setPreferredSize(new java.awt.Dimension(300, 351));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(103, 243, 193));
        jLabel1.setText("Alumno Elegido");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(103, 243, 193))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Nombre:");

        txt_AlumnoNombre.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoNombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setText("Nombre");
        txt_AlumnoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_AlumnoNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoNombre.setDoubleBuffered(true);
        txt_AlumnoNombre.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Apellido:");

        txt_AlumnoApellido.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoApellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setText("Apellido");
        txt_AlumnoApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_AlumnoApellido.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoApellido.setDoubleBuffered(true);
        txt_AlumnoApellido.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Carrera Inscripto:");

        txt_AlumnoCarreraNombre.setEditable(false);
        txt_AlumnoCarreraNombre.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoCarreraNombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setText("Nombre Carrera");
        txt_AlumnoCarreraNombre.setBorder(null);
        txt_AlumnoCarreraNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraNombre.setDoubleBuffered(true);
        txt_AlumnoCarreraNombre.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Codigo:");

        txt_AlumnoCarreraCodigo.setEditable(false);
        txt_AlumnoCarreraCodigo.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoCarreraCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setText("Codigo");
        txt_AlumnoCarreraCodigo.setBorder(null);
        txt_AlumnoCarreraCodigo.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoCarreraCodigo.setDoubleBuffered(true);
        txt_AlumnoCarreraCodigo.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Agregar Materia");

        bt_ConfirmAgregarMateria.setBackground(new java.awt.Color(103, 243, 193));
        bt_ConfirmAgregarMateria.setForeground(new java.awt.Color(51, 51, 51));
        bt_ConfirmAgregarMateria.setText("Agregar");
        bt_ConfirmAgregarMateria.setBorder(null);

        txt_AlumnoResidencia.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoResidencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setText("Lugar de residencia");
        txt_AlumnoResidencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_AlumnoResidencia.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoResidencia.setDoubleBuffered(true);
        txt_AlumnoResidencia.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Residencia:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Numero Telefonico:");

        txt_AlumnoTelefono.setBackground(new java.awt.Color(102, 102, 102));
        txt_AlumnoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setText("Telefono");
        txt_AlumnoTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_AlumnoTelefono.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_AlumnoTelefono.setDoubleBuffered(true);
        txt_AlumnoTelefono.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Fecha de Inscripcion:");

        txt_InscripcionFecha.setEditable(false);
        txt_InscripcionFecha.setBackground(new java.awt.Color(102, 102, 102));
        txt_InscripcionFecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setText("0000-00-00");
        txt_InscripcionFecha.setBorder(null);
        txt_InscripcionFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_InscripcionFecha.setDoubleBuffered(true);
        txt_InscripcionFecha.setSelectionColor(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(list_AlumnoMaterias);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Materias:");

        bt_ConfirmarCambios.setBackground(new java.awt.Color(103, 243, 193));
        bt_ConfirmarCambios.setForeground(new java.awt.Color(51, 51, 51));
        bt_ConfirmarCambios.setText("Aplicar Cambios");
        bt_ConfirmarCambios.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AlumnoCarreraNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AlumnoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AlumnoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(cb_SelectMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_ConfirmAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AlumnoCarreraCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_InscripcionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_AlumnoTelefono))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_AlumnoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_ConfirmarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_AlumnoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_AlumnoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_AlumnoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_AlumnoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_AlumnoCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_AlumnoCarreraCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_InscripcionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ConfirmAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_SelectMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_ConfirmarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(103, 243, 193));
        jPanel3.setForeground(new java.awt.Color(103, 243, 193));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Nombre Completo:");

        txt_SelectAlumno.setBackground(new java.awt.Color(102, 102, 102));
        txt_SelectAlumno.setForeground(new java.awt.Color(255, 255, 255));
        txt_SelectAlumno.setText("Nombre");
        txt_SelectAlumno.setBorder(null);
        txt_SelectAlumno.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_SelectAlumno.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_SelectAlumno.setDoubleBuffered(true);
        txt_SelectAlumno.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("DNI:");

        txt_SelectAlumnoDni.setEditable(false);
        txt_SelectAlumnoDni.setBackground(new java.awt.Color(102, 102, 102));
        txt_SelectAlumnoDni.setForeground(new java.awt.Color(255, 255, 255));
        txt_SelectAlumnoDni.setText("Dni");
        txt_SelectAlumnoDni.setBorder(null);
        txt_SelectAlumnoDni.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_SelectAlumnoDni.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_SelectAlumnoDni.setDoubleBuffered(true);
        txt_SelectAlumnoDni.setSelectionColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_SelectAlumnoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_SelectAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_SelectAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_SelectAlumnoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBt_ConfirmAgregarMateria() {
        return bt_ConfirmAgregarMateria;
    }

    public JButton getBt_ConfirmarCambios() {
        return bt_ConfirmarCambios;
    }

    public JTextField getTxt_SelectAlumno() {
        return txt_SelectAlumno;
    }

    public JTextField getTxt_SelectAlumnoDni() {
        return txt_SelectAlumnoDni;
    }

    

    public JComboBox<Object> getCb_SelectMateria() {
        return cb_SelectMateria;
    }

    public JTextField getTxt_AlumnoApellido() {
        return txt_AlumnoApellido;
    }

    public JTextField getTxt_AlumnoCarreraCodigo() {
        return txt_AlumnoCarreraCodigo;
    }

    public JTextField getTxt_AlumnoCarreraNombre() {
        return txt_AlumnoCarreraNombre;
    }


    public JTextField getTxt_AlumnoNombre() {
        return txt_AlumnoNombre;
    }

    public JTextField getTxt_AlumnoResidencia() {
        return txt_AlumnoResidencia;
    }

    public JTextField getTxt_AlumnoTelefono() {
        return txt_AlumnoTelefono;
    }
    

    public JTextField getTxt_InscripcionFecha() {
        return txt_InscripcionFecha;
    }

    public void setTxt_InscripcionFecha(JTextField txt_InscripcionFecha) {
        this.txt_InscripcionFecha = txt_InscripcionFecha;
    }

    public JList<Object> getList_AlumnoMaterias() {
        return list_AlumnoMaterias;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ConfirmAgregarMateria;
    private javax.swing.JButton bt_ConfirmarCambios;
    private javax.swing.JComboBox<Object> cb_SelectMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Object> list_AlumnoMaterias;
    private javax.swing.JTextField txt_AlumnoApellido;
    private javax.swing.JTextField txt_AlumnoCarreraCodigo;
    private javax.swing.JTextField txt_AlumnoCarreraNombre;
    private javax.swing.JTextField txt_AlumnoNombre;
    private javax.swing.JTextField txt_AlumnoResidencia;
    private javax.swing.JTextField txt_AlumnoTelefono;
    private javax.swing.JTextField txt_InscripcionFecha;
    private javax.swing.JTextField txt_SelectAlumno;
    private javax.swing.JTextField txt_SelectAlumnoDni;
    // End of variables declaration//GEN-END:variables
}
